
services:
  api_gateway:
    build: ./api_gateway
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app-network

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
